import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFC12F);
const kSecondaryColor = Color(0xFFFFE6AC);
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductCategory = 'productCategory';
const kProductLocation = 'productLocation';
const kProductsCollections = 'products';
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = 'earphone';
const kTshirts = 't-shirts';
const kTrousers = 'trousers';
const kShoes = 'shoes';
const kOrders = 'orders';
const kOrderDetails = 'orderDetails';
const kTotalPrice = 'totalPrice';
const kAddress = 'address';
const kStatus = 'status';
const kUserId = 'userid';
const kImage = 'image';
const kProductQuantity = 'productQuantity';
const kpQuantity = 'pQuantity';
const kKeepMeLoggedIn = 'keepMeLoggedIn';
String kGetUID = 'getUID';
